on:
  push:
  pull_request:
  workflow_dispatch:

name: Test - Kustomization
jobs:

  # Test updating only image without env
  test-image:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-latest]
    name: Test - Image [${{ matrix.os }}]
    runs-on: ${{ matrix.os }}
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v7

    - name: Bake
      run: kustomize build './test/kustomize' > deployment.yaml

    - name: Update with dynamic uses [${{ steps.branch-name.outputs.current_branch }}]
      uses: jenseng/dynamic-uses@v1
      with:
        uses: JonathanAtCenterEdge/update-deployment-yaml@${{ steps.branch-name.outputs.current_branch }}
        with: '{ "image": "${{ github.sha }}", "container": "whoami-container", "deployment": "./deployment.yaml" }'

    - run: ls

    - name: Container should contain new image version
      uses: GuillaumeFalourd/assert-command-line-output@v3
      with:
        command_line: ls
        contains: "image: ${{ github.sha }}"
        expected_result: PASSED

    - run: cat ./deployment.yaml

  # Test updating only env
  test-env:
    name: Test - Env
    runs-on: ubuntu-22.04
    steps:

    - name: Checkout
      uses: actions/checkout@v3

  # Test updating only multiline env
  test-env-multi:
    name: Test - Env multiline
    runs-on: ubuntu-22.04
    steps:

    - name: Checkout
      uses: actions/checkout@v3

  # Test updating image and env
  test-image-env:
    name: Test - Image & Env
    runs-on: ubuntu-22.04
    steps:

    - name: Checkout
      uses: actions/checkout@v3
