on:
  push:
  pull_request:
  workflow_dispatch:

name: Test - Kustomization
jobs:
  test-image:
    name: Test - Image
    runs-on: ubuntu-22.04
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Bake
      run: kustomize build './test/kustomize' > deployment.yaml

    - name: Update
      uses: JonathanAtCenterEdge/update-deployment-yaml@main
      with:
        image: traefik/whoami:v1.9 # new image version
        container: whoami-container # the container in the deployment matching via name property
        deployment: ./deployment.yaml # the deployment file, usually this has already been baked by kustomize
        env: TEXT_RESPONSE=test # a list of environment variables to replace, comma seperated and optionally multieline

    - run: cat ./deployment.yaml
