on:
  push:
  pull_request:
  workflow_dispatch:

name: Test - Kustomization
jobs:
  test-image:
    name: Test - Image
    runs-on: ubuntu-22.04
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Kustomize - Build
      run: kustomize build './test/kustomize' > deployment.yaml

    - name: Update - Image
      uses: JonathanAtCenterEdge/update-deployment-yaml@$GITHUB_REF
      with:
        image: test
        container: whoami-container
        deployment: ./deployment.yaml
      env:
        RateLimiting__CreditCardPages__CountLimit: asdsa
        RateLimiting__CreditCardPages__CountLimit1: asdsa
        RateLimiting__CreditCardPages__CountLimit2: asdsa

    - run: cat ./deployment.yaml
