on:
  push:
  pull_request:
  workflow_dispatch:

name: Test - Kustomization
jobs:
  test-image:
    name: Test - Image
    runs-on: ubuntu-22.04
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v7

    - name: Bake
      run: kustomize build './test/kustomize' > deployment.yaml

    - name: Update with dynamic uses
      uses: jenseng/dynamic-uses@v1
      with:
        uses: JonathanAtCenterEdge/update-deployment-yaml@${{ steps.branch-name.outputs.current_branch }}
        with: '{ "image": "${{ github.sha }}", "container": "whoami-container", "deployment": "./deployment.yaml" }'

    - uses: GuillaumeFalourd/assert-command-line-output@v2
      with:
        command_line: cat ./deployment.yaml
        contains: "image: ${{ github.sha }}"
        expected_result: PASSED

    - run: cat ./deployment.yaml
